#!/bin/sh

BRANCH=systemd

# Debian paths
### set git cloned location
REPO_PATH=/opt/emonhub

### set location to install emonhub.py etc
INST_PATH=/usr/local/bin

CONF_PATH=/etc/emonhub

###install dependancies
apt-get update && apt-get install -y python-pip python-serial python-configobj
#apt-get update && apt-get install -y python-pip 
#apt-get purge python-serial && apt-get clean
#pip install pyserial configobj #paho-mqtt

### create "emonhub" user
useradd -M -r -G dialout,tty -c "emonHub user" emonhub

### clone emonhub
mkdir -p $REPO_PATH && git clone https://github.com/emonhub/emonhub.git $REPO_PATH/emonhub -b $BRANCH

### create folder and move settings file (unless it exists already)
if [ ! -f /etc/emonhub/emonhub.conf ] ; then
  mkdir -p $CONF_PATH && cp $REPO_PATH/conf/emonhub.conf $CONF_PATH
fi

### create linked directory for emonhub.py etc
mkdir -p $INST_PATH && ln -sfn $REPO_PATH/emonhub/src $INST_PATH/emonhub

### systemd unit
ln -sf $REPO_PATH/service/emonhub.service /etc/systemd/system/emonhub.service

# launch at start-ip
systemctl enable --now emonhub.service

### delete install script
#sudo rm -r `dirname $0`
